module.exports = ctx => ({
  map: !ctx.env || ctx.env !== 'production' ? { inline: false } : false,
  syntax: 'postcss-scss',
  plugins: [
    require("postcss-calc"),
    require('autoprefixer')({
      cascade: false
    }),
    require('postcss-header')({
      header: `DO NOT EDIT THIS FILE.\nSee the following change record for more information,\nhttps://www.drupal.org/node/3084859\n@preserve`,
    }),
  ]
});
